config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'
  resources :cocktails, only: [:index, :new, :show, :create] do
    resources :doses, only: [:index, :show, :new, :create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: 'dose'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  # Through set le has many ingredient via la table doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # created using : rails generate controller Cocktails index show new create delete


  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # created using : rails generate controller doses index show new create delete
  #before_action :find_cocktails, only: [ :new, :create ]

  def index
    @doses = Dose.all
  end

  def show
    find_cocktail
    @dose = Dose.find(params[:id])
  end

  def new
    find_cocktail
    @dose = Dose.new
  end

  def create
    find_cocktail
    # il faut créer une dose consolidée avec les données cocktails
    @dose = @cocktail.doses.build(dose_params)
    respond_to do |format|
      if @dose.save
        format.html { redirect_to @cocktail, notice: 'Dose was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :name, :cocktail_id, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.button :submit %>
<% end %>

app/views/cocktails/index.html.erb
<%= render "shared/banner" %>

<h1 class = "text-center">Cocktails inspiration</h1>
<br>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-lg-4">
        <!-- insert <div class="card"> -->
          <div class="card" style="background-image: image-url("<%= cocktail.name + '.png' %>")>
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
              <p>Very cool stuff, useful and smart</p>
              <%= link_to '+', cocktail, {class: "btn btn-primary"} %>
            </div>

          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<br>
<div class="container">
  <div class="row">
    <div class=" col-sm-offset-3 col-sm-4 bg-gre">
      <h1>Cocktails#new</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4 bg-gre">
      <h1><%= @cocktail.name %></h1>
      <% @cocktail.doses.each do |dose| %>
        <ul>
          <li>
            <p>
            <%= dose.description %> of
            <%= Ingredient.find(dose.ingredient_id).name %>
            <%= link_to "", dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash" %>
            </p>
          </li>
        </ul>
      <% end %>
      <br>
      <p><%= link_to 'Add new dose', new_cocktail_dose_path(@cocktail), {class: "btn btn-danger"} %></p>
      <p><%= link_to 'back', cocktails_path, {class: "btn btn-danger"} %></p>
    </div>
  </div>
</div>

app/views/doses/_form_dose.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description %>

  <%= f.association :ingredient %>

  <%= f.button :submit %>
<% end %>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<br>
<div class="container">
  <div class="row">
    <div class=" col-sm-offset-3 col-sm-4 bg-gre">
      <h1>Doses#new</h1>
      <%= render 'form_dose' %>
    </div>
  </div>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>RailsMisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/navbar" %>
<%= yield %>

</body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" id = "banner-picture">
  <div class="banner-content">
    <h1>Drink Classy</h1>
    <p>Best Cocktails in town</p>
    <a class="btn btn-danger btn-lg">Discover</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "noun_364552_cc.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %> -->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to "New Cocktail",  new_cocktail_path, {class: "btn btn-danger"} %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>